CREATE TABLE friendships (
    id SERIAL PRIMARY KEY,
    user1 INT NOT NULL,
    user2 INT NOT NULL,
    is_new1 BOOLEAN NOT NULL DEFAULT TRUE,
    is_new2 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user1) REFERENCES users (id),
    FOREIGN KEY (user2) REFERENCES users (id)
);