CREATE TABLE level_reports (
    id SERIAL PRIMARY KEY,
    level_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (level_id) REFERENCES levels (id) ON DELETE CASCADE
);